export const NodeType = {
    INITIAL: "INITIAL",
    MANUAL_TRIGGER: "MANUAL_TRIGGER",
    HTTP_REQUEST: "HTTP_REQUEST",
    IF_CONDITION: "IF_CONDITION",
    SWITCH: "SWITCH",
    LOOP: "LOOP",
    WAIT: "WAIT",
    AI_AGENT: "AI_AGENT",
    AI_GENERATE: "AI_GENERATE",
    AI_EXTRACT: "AI_EXTRACT",
    AI_CLASSIFY: "AI_CLASSIFY",
    AI_AGENT_EXP: "AI_AGENT_EXP",
    GROUP: "GROUP",
    ANNOTATION: "ANNOTATION",
} as const;

export type NodeType = string;
